---
title: "Path analysis for jamovi"
topic: glm
category: help
output: 
  html_document:
     includes:
         in_header: ganalytics.txt
     toc: true
     toc_float:
        collapsed: false
bibliography: 
     - bib.bib
     - bib.yaml
link-citations: true

---


```{r echo=FALSE,results='hide'}
source("../R/constants.R")
source("../R/functions.R")
```

`r keywords("pathj,jamovi, path analyis")`

**PATHJ** module of the PATHj suite for jamovi

`r version("0.2.*")` 
`r draft`


# Introduction

The `r modulename` module represents a `r jamovi` interface to `lavaan` R package [@lavaan]. It implements path analysis, so SEM models with observed variables (no latent variables). The module handles continuous dependent (endogenous) variables, continuous and categorical independent (exogenous) variables, linear and interaction effects. Path diagrams are available thanks to R package `semPlot` [@semplot]. Please refer to these package help for detail about the model estimation and path diagrams features.  

# User Interface

To open `r modulename`, one clicks on the `SEM` menu, and then `Path Analysis` under `pathj`.

Like any `r jamovi` module, the input user interface resides on the left panel of the `Analysis` pane. All options are in foldable panels, divided more or less by topic. The only not foldable panel is the variable role definition panel, the one at the top.

`r pic("pics/help/input_variables_role.png")`

To run a model, we first select the variables and their role. `Endogenous Variables` are the one that will receive a path in the final model. Exogenous Variables are specified depending on their measurement levels. Categorical exogenous go in `Exogenous Factors`, continuous variables for in `Exogenous Covariates`. 

Factors are handled by decomposing the variable in K-1 contrast variable and insert in the model in place of the categorical variable. The type of contrast used, for each factor, can be seen in the `Factor Coding` tab.

Continuous variable are left unchanged, but their scale can be changed in the `Continuous Variables Scaling` tab, for easily centering, or standardizing the variables. 

`Multigroup Analysis Factor` is used to run multigroup analyses.

A model with two endogenous variables, one continuous and one factor as exogenous predictors is sets ar follows:

`r pic("pics/help/input_variables_filled.png")`

## Endogenous Models

Here we specify each endogenous variable predictors. First one selects on the right panel the endogenous model that needs to be set, then select the predictor(s) and fill the field with the arrow. Interactions among predictors are included by selecting more then one term on the left, and bring the on the right panel with the arrow.

`r pic("pics/help/input_endogenous.png")`

In this example, `y1` is predicted by `y2`, `x3` and `groups_a` variables, whereas `y2` is predicted by `x3` and `groups_a`. 

## Variances and Covariances

By default, `r modulename` estimate the variances and the covariances among endogenous variables. More pricesily, among variables that represent end nodes of the path diagram. This behavior is controlled by the option `Free Parameters -> Endogenous Correlations`. If not selected, only the variances are estimated, and the covariances are set to 0. 

The variances and covariances of the exogenous variables are computed from the sample data. In case one wants to estimate the population variances and covariances also for the exogenous variables, one should de-select the option `Miscellaneous -> Fixed Exogenous` in the `Parameters Options` panel, or select the terms pair and bring it in the right panel.

Any variance or covariance not already present in the model can be estimated by selecting the appropriate terms pair on the left panel and bring it to the right panel. In this example, the estimation of the variance of variable `x3` is required.


`r pic("pics/help/input_varcov.png")`




# Examples

Some worked out examples of the analyses carried out with jamovi PATHj are posted here (more to come)

`r include_examples("pathj")`

# Details

Some more information about the module specs can be found here

`r include_details("pathj")`


`r issues()`

'
